# -*- mode: ruby -*-
# vi: set ft=ruby :
required_plugins = %w(  vagrant-reload )
required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "datacastle/windows7"
  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
   config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
     vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
     vb.memory = "2048"
   end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
   config.vm.provision "shell",
    inline: "cd C:\\Users\\vagrant\\Desktop; mkdir visual_studio; cd visual_studio; wget -outf vs.exe download.microsoft.com/download/D/B/C/DBC11267-9597-46FF-8377-E194A73970D6/vs_proweb.exe; Start-Process \"vs.exe\" -ArgumentList \"/Passive\" -Wait"  
   config.vm.provision "shell", inline:<<-SHELL
    cd 'C:\\Users\\vagrant\\Desktop'
    mkdir pex
    cd pex
    wget -Outfile pex.msi http://ftp.research.microsoft.com/downloads/d2279651-851f-4d7a-bf05-16fd7eb26559/pex.academic.x86.msi 
    Start-Process .\\pex.msi /q -Wait
    SHELL
   config.vm.provision "shell", inline:<<-SHELL
    # copy contents from synced folder
    xcopy "C:\\vagrant\\License.txt" "C:\\Users\\vagrant\\Desktop"
    xcopy "C:\\vagrant\\README.txt" "C:\\Users\\vagrant\\Desktop"
    xcopy "C:\\vagrant\\Installation.txt" "C:\\Users\\vagrant\\Desktop"
    xcopy "C:\\vagrant\\Covana_youtube.url" "C:\\Users\\vagrant\\Desktop"
    mkdir Covana
    xcopy /s /i /e "C:\\vagrant\\Covana" "C:\\Users\\vagrant\\Desktop\\Covana"
    #create Desktop shortcut
    $TargetFile = ""C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\Common7\\IDE\\devenv.exe"
    $ShortcutFile = "C:\\Users\\vagrant\\Desktop\\devenv.exe.lnk"
    $WScriptShell = New-Object -ComObject WScript.Shell
    $Shortcut = $WScriptShell.CreateShortcut($ShortcutFile)
    $Shortcut.TargetPath = $TargetFile
    $Shortcut.Save()
    xcopy 'C:\\Users\\vagrant\\Desktop\\devenv.exe.lnk' 'C:\\Users\\vagrant\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup'
    SHELL
    #Restart for the changes to take effect
    #config.vm.provision :reload
    
end
